language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
before_install:
    # install prereqs
    - "cpanm Moose"
    - "cpanm Expect"
    - "cpanm Test::NoWarnings"
    - "cpanm Test::Exception"
    # install dist development dependencies
    - "dzil authordeps | xargs cpanm"
    - "export tmpbuild=`mktemp --directory`"
    - "dzil build --in $tmpbuild"
    - "perl -MCPAN::Meta -e '$,=\"\\n\"; print CPAN::Meta->load_file(\"$ENV{tmpbuild}/META.json\")->effective_prereqs->requirements_for(\"develop\", \"requires\")->required_modules' | xargs cpanm"
install: "dzil listdeps | xargs cpanm"
script: "dzil test --release && cover -test -report coveralls"
